### ISSUE TITLE
When creating a new project, add owner to project_members table

### ISSUE THREAD

**Issue by jslvtr** [jslvtr/AgileAPI#14]
^

**Comment by stuartjdouglas** [comment]
this has been done?

**Comment by jslvtr** [comment]
Not yet

**Comment by stuartjdouglas** [comment]
huh thats weird, cause that was a fix I did yesterday... I'll try and see where it is or fix it again

**Comment by stuartjdouglas** [comment]
please verify PR https://github.com/jslvtr/AgileAPI/pull/15

**Comment by jslvtr** [comment]
PR #15 fixed this.
