### ISSUE TITLE
Missing projects member of

### ISSUE THREAD

**Issue by stuartjdouglas** [jslvtr/AgileAPI#25]
We get a list of projects that we own but not what we are member of.

Please check

**Comment by jslvtr** [comment]
I'm on it.

**Comment by stuartjdouglas** [comment]
wasn't sure if you had already implemented it

**Comment by jslvtr** [comment]
It will involve re-structuring the database.

Actually, it may not.

**Comment by stuartjdouglas** [comment]
if you make sure it doesn't affect the rest of the code that should be fine

**Comment by jslvtr** [comment]
I think I may have the solution, it's not too clean but didn't really see a way around it with the current architecture. Will test and PR.

**Comment by jslvtr** [comment]
This has been fixed with #28
