### ISSUE TITLE
If user already exists, no message is returned

### ISSUE THREAD

**Issue by jslvtr** [jslvtr/AgileAPI#4]
Is this by design? In the code, there is a message to be returned, but this doesn't come back since the HTTP status code is `NO_CONTENT`.

**Comment by stuartjdouglas** [comment]
when using the http_status NO_CONTENT it is normal for it to just return nothing. it returns the status code but won't return any data. 

Not sure why

**Comment by YagoCarballo** [comment]
yep, 204 and 205 mean no content, and no content but there where changes, and so.., the server is not supposed to send anything, (depending on the implementation some send stuff.... others don't...)

**Comment by jslvtr** [comment]
This has been fixed at some point over the past week.
