### ISSUE TITLE
If project doesn't exist but it gets deleted, an "Accepted" response is still returned

### ISSUE THREAD

**Issue by jslvtr** [jslvtr/AgileAPI#8]
I'm trying to delete a project that doesn't exist, but I'm still getting a `202 Accepted` response.

Is there any way to check? Maybe we need to search for the project we just deleted and see if it still exists or not?

Or maybe it can't be done because Cassandra.

**Comment by stuartjdouglas** [comment]
If we want to get another response we would need to do another query to check if the project exists or not, which at this point isn't really worth doing until we have the other use cases working. 

Though if you really want it to be added just say
